/*
 * 按照key->value 书写文件名和对应页面
 * */
var URL = {
    'test.html': '创建项目测试文件',
    "paging.html": "分页样式",
    'base-template.html': '项目基本模板文件',
    'go-school.html': '首页-进入学校',
    'create-school.html': '首页-进入学校-创建校区',
    'org-manage.html': '组织管理',
    'class-details.html': "班级管理-班级详情",
    'look-classmanage.html': "班级管理-查看班级-校长超管",
    "learn-study.html": "班级管理-查看班级-学管主任",
    "area-supermanage.html": "区域管理-超管",
    "area-detailmanage.html": "区域管理-经理详情",
    "area-deletemanage.html": "区域管理-删除校区",
    'student-detail.html': '学生详情',
    "systemset-personality.html": "系统设置-个性化设置",
    "systemset-orgmanage.html": "系统设置-机构管理设置",
    "paper.html": "教案情况-教案情况",
    "paper-details.html": "教案情况-教案详情页",
    'pop-up2.html': '顶部不是红色的弹框（主要是提示作用的弹框） / 部门无数据的页面显示  /创建失败提示',
    "teach-branch-manage.html": "教学监管-教学情况-分校管理员",
    "teach-super-manage.html": "教学监管-超管",
    "homework-detail.html": "教学-作业详情",
    "login.html": '登录页',
    "assembly.html": '组卷(根据知识点)',
    "paper-list.html": '试卷列表',
    "evaluation-archives.html": "咨询管理（咨询主任）- 测评档案-咨询管理-咨询主任",
    "sign-contact-stu.html": "咨询管理（咨询主任）- 已签约学生-咨询管理-咨询主任",
    "sign-up.html": "咨询管理（咨询师）- 报名签约",
    "wrong-topic.html": "学生情况-教学监管-错题本",
    "homework-condition.html": '学生作业情况',
	"filterTest.html.html":"试题筛选",
	"noData-403.html":'404页面',
	"subject-test.html":"知识测评-咨询师-学科测评",
    "learn-test.html":"知识测评-咨询师-学能测评",
    "add-student.html": '学生管理-添加学生',
    "personCenter.html":'个人中心-基本资料编辑',
    "teach-records.html":"学生情况-教学监管-教学记录",
    "editTeachMeg.html":'个人中心-教学信息',
    "base-meg-show.html":'个人中心-基本资料展示',
    "teach-meg-show.html":'个人中心-教学信息',
    "mysuggess.html":'个人中心-意见反馈',
    "userPass.html":'个人中心-账号密码',
    "distribute-tea.html":"分配老师-班级-学管",
    "aptitude-test-list.html":"学能类试卷列表",
    "edit-not-teacher-detail.html": '编辑非老师详情',
    "edit-student-detail.html": '编辑学生详情',
    "knowledge-test.html": '学生情况-知识测评',
    "master-analys.html":'学生情况-掌握分析',
    "not-teacher-detail.html": '非老师详情',
    "subject-answer-card.html": '学科答题卡',
    "learn-card.html":"学能答题卡",
    "before-answer-prompt.html":"答题前提示",
    "fill-stu-news.html":"填写学生信息",
    "see-subject-evaluation.html": '查看学生测评报告',
    "see-learn-evaluation.html":"查看学能测试报告"
};